version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: clinicweb
      MONGO_INITDB_ROOT_PASSWORD: clinicweb
      ME_CONFIG_MONGODB_URL: mongodb://clinicweb:clinicweb@mongo:27017/clinicweb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      app-network:

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    # Important to bind/mount your codebase dir to /app dir for live reload
#    volumes:
#      - ./:/app
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
