// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"clinicweb/internal/modules/doctor/infra/repository"
	"clinicweb/internal/modules/doctor/infra/web"
	"clinicweb/internal/modules/doctor/usecase"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func NewCreateDoctorUseCase(collection *mongo.Collection) *usecase.CreateDoctorUseCase {
	doctorRepository := repository.NewDoctorRepository(collection)
	createDoctorUseCase := usecase.NewCreateDoctorUseCase(doctorRepository)
	return createDoctorUseCase
}

func NewWebDoctorHandler(collection *mongo.Collection) *web.DoctorHandler {
	doctorRepository := repository.NewDoctorRepository(collection)
	doctorHandler := web.NewWebDoctorHandler(doctorRepository)
	return doctorHandler
}

// wire.go:

var setDoctorRepositoryDependency = wire.NewSet(repository.NewDoctorRepository, wire.Bind(new(repository.DoctorRepositoryInterface), new(*repository.DoctorRepository)))
